server:
  address: "127.0.0.1"
  port: 8080

github:
  v3_api_url: "https://api.github.com/" # for GitHub Enterprise, use "https://<your-github-enterprise-host>/api/v3/"
  app:
    integration_id: 0 # you App's ID
    webhook_secret: "" # your App's webhook secret
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----

azure:
  storage_account_name: ""